name: schedule
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  formz: ^0.7.0
  google_fonts: ^6.2.1
  meta: ^1.15.0
  google_sign_in: ^6.2.2
  http: ^1.2.2
  dio: ^5.7.0
  intl: ^0.20.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.17
  firebase_auth: ^5.4.1
  firebase_messaging: ^15.2.1
  gap: ^3.0.1
  calendar_view: ^1.4.0
  get_it: ^8.0.3
  auto_size_text: ^3.0.0
  flutter_local_notifications: ^18.0.1
  

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/logos/
  - assets/icons/
  - assets/icons/todayIcon.svg
  - assets/icons/weekIcon.svg
  - assets/icons/profileIcon.svg
  - assets/images/avatarImage.jpg
