// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqM93Q6mQe8CgsvCXqpwvPYhZ2JGR-vUM',
    appId: '1:909820019815:web:a63272e97d5e61ce4040c2',
    messagingSenderId: '909820019815',
    projectId: 'schedule-b6d27',
    authDomain: 'schedule-b6d27.firebaseapp.com',
    storageBucket: 'schedule-b6d27.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvox0YGlIlxEF9TMJwZ-V3yIOVgGqPuRk',
    appId: '1:909820019815:android:1b43f2ae729c6ee24040c2',
    messagingSenderId: '909820019815',
    projectId: 'schedule-b6d27',
    storageBucket: 'schedule-b6d27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnPNVOn6quzZJNAFfTtT55hJ-lLpBUE9o',
    appId: '1:909820019815:ios:367d494c0021027e4040c2',
    messagingSenderId: '909820019815',
    projectId: 'schedule-b6d27',
    storageBucket: 'schedule-b6d27.firebasestorage.app',
    iosClientId: '909820019815-c73sttv8o43jc2bifug8h0sclliedta2.apps.googleusercontent.com',
    iosBundleId: 'com.example.schedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnPNVOn6quzZJNAFfTtT55hJ-lLpBUE9o',
    appId: '1:909820019815:ios:367d494c0021027e4040c2',
    messagingSenderId: '909820019815',
    projectId: 'schedule-b6d27',
    storageBucket: 'schedule-b6d27.firebasestorage.app',
    iosClientId: '909820019815-c73sttv8o43jc2bifug8h0sclliedta2.apps.googleusercontent.com',
    iosBundleId: 'com.example.schedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqM93Q6mQe8CgsvCXqpwvPYhZ2JGR-vUM',
    appId: '1:909820019815:web:1e8a9bae08a610734040c2',
    messagingSenderId: '909820019815',
    projectId: 'schedule-b6d27',
    authDomain: 'schedule-b6d27.firebaseapp.com',
    storageBucket: 'schedule-b6d27.firebasestorage.app',
  );
}
